# This is a configuration example providing the Backstitch Webviewer.
services:
  backstitch-webviewer:
    image: ghcr.io/inkandswitch/backstitch-webviewer:latest
    environment:
      BACKSTITCH_API_URL: / # we're serving this at the root of our API
    volumes:
      - webviewer:/site
 
  backstitch-sync-server:
    image: ghcr.io/inkandswitch/backstitch-sync-server:latest
    restart: unless-stopped
    environment:
      # The authentication scheme to use. This MUST be specified.
      AUTH: "none"
      # Recommend ourselves as the webviewer.
      # If your webviewer is hosted elsewhere, this can take an absolute or relative URL.
      WEBVIEWER: "/"
      # The static site content path. In this case, we mounted it to /webviewer.
      WEBVIEWER_PATH: "/webviewer"
      # If you are using AUTH: "oidc", this must be specified as "true" to use the webviewer.
      # This means that anyone will be able to access the webviewer, even if they don't have an account!
      # If you're using AUTH: "none", the data is publically accessible anyways and this setting
      # will have no effect.
      NO_WEBVIEWER_AUTH: "false"
      # Highly recommended: Include a signing key.
      SIGNING_KEY: backstitch_signing_key

    # Setting this to "80", as shown, will expose the HTTP server directly.
    # If you have a domain name, we highly recommend using a HTTPS reverse-proxy
    # service like Caddy instead.
    # For an example with Caddy, see `docker-compose.caddy.yaml`. 
    ports:
      - "80:3000"
      
    secrets:
      - backstitch_signing_key

    volumes:
      # For data persistance, mount this backstitch-data volume.
      - backstitch-data:/data
      # Mount the built webviewer image volume to /webviewer
      - webviewer:/webviewer

secrets:
  # This file should contain a randomly-generated, 32-byte hex string to use as the signing key.
  backstitch_signing_key: ./your/secret/path/backstitch_signing_key.txt

volumes:
  webviewer:
  backstitch-data:
