services:
  backstitch-sync-server:
    image: ghcr.io/inkandswitch/backstitch-sync-server:latest
    restart: unless-stopped
    environment:
      # The authentication scheme to use. This MUST be specified.
      # When using AUTH: "none", it is highly recommended to hide the server behind a VPN tunnel service like Tailscale or ZeroTier.
      # Those will provide secure, easy authentication setup.
      AUTH: "none"
    ports:
      - "80:3000" # Change the first part to the desired external HTTP server port. This will be the port entered into the Backstitch client.
                  # If you don't want to enter a port in the Backstitch client, it defaults to port 80. (TODO: Change this to 443 when we have HTTPS?)
    volumes:
      # For data persistance, mount this backstitch-data volume.
      - backstitch-data:/data

volumes:
  backstitch-data:
