# This is a configuration example with OpenID Connect.
# You'll need an OpenID Connect authentication endpoint, in addition to this server.
# This is recommended only for advanced users with an existing SSO OAuth backend.
services:
  backstitch-sync-server:
    image: ghcr.io/inkandswitch/backstitch-sync-server:latest
    restart: unless-stopped
    environment:
      # The authentication scheme to use. This MUST be specified.
      AUTH: "oidc"
      # The OpenID Connect issuer URL to authenticate with.
      OIDC_ISSUER: "https://example.com"
      # The OpenID Connect Client ID registered with your OIDC provider.
      OIDC_CLIENT_ID: "backstitch"
      # The port of the OpenID Connect Redirect URL registered with your OIDC provider. This can be an arbitrary port.
      # By default, it is 58656.
      # The full registered redirect URL must be "http://localhost:PORT"!
      OIDC_REDIRECT_PORT: "58656"
      # Some OIDC providers require the `resource` parameter to be set to a specific URL to grant access.
      # This parameter tells Backstitch to use that URL.
      OIDC_RESOURCE: "https://api.example.com"
      # Highly recommended: Include a signing key.
      SIGNING_KEY: backstitch_signing_key

    # Setting this to "80", as shown, will expose the HTTP server directly.
    # If you have a domain name, we highly recommend using a HTTPS reverse-proxy
    # service like Caddy instead.
    # For an example with Caddy, see `docker-compose.caddy.yaml`. 
    ports:
      - "80:3000"

    secrets:
      - backstitch_signing_key

    volumes:
      # For data persistance, mount this backstitch-data volume.
      - backstitch-data:/data
      
secrets:
  # This file should contain a randomly-generated, 32-byte hex string to use as the signing key.
  backstitch_signing_key: ./your/secret/path/backstitch_signing_key.txt

volumes:
  backstitch-data:
